spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gtb?characterEncoding=utf-8
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


